version: "3.6"
services:
  axonserver:
    image: axoniq/axonserver:latest
    restart: always
    hostname: axonserver
    volumes:
      - axonserver_data:/data
      - axonserver_events:/eventdata
    ports:
      - '8024:8024'
      - '8124:8124'
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_data:
  axonserver_data:
  axonserver_events:
