### OnBoardingRequestTrial Command
POST http://localhost:3100/api/command
Content-Type: application/json

{
  "businessCapability": "OnBoarding",
  "command": "RequestTrial",
  "payload": {
     "email" : "Test@test.com",
     "firstName" : "A",
     "lastName" : "B"
  }
}

> {%
  client.global.set('OnBoardingRequestTrialId', response.body.OnBoardingRequestTrialId)
%}
